// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/identity-book/Current.tsx": () => import("../components/mockups/identity-book/Current.tsx"),
  "./components/mockups/identity-book/InteractiveContents.tsx": () => import("../components/mockups/identity-book/InteractiveContents.tsx"),
  "./components/mockups/identity-book/InteractiveReading.tsx": () => import("../components/mockups/identity-book/InteractiveReading.tsx")
};
